-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.1 (64-bit) Schlumberger
-- User name   : ntvuong
-- Date        : Wednesday, June 17 2020 15:20:44
-- Project     : 40402.pet
-- Generated ]

FOEIW                                  -- Generated : Petrel

FOEIG                                  -- Generated : Petrel

FOE                                    -- Generated : Petrel

FWGR                                   -- Generated : Petrel

FWCT                                   -- Generated : Petrel

FRV                                    -- Generated : Petrel

TIMESTEP                               -- Generated : Petrel

FRS                                    -- Generated : Petrel

FVPR                                   -- Generated : Petrel

FVPT                                   -- Generated : Petrel

FVIR                                   -- Generated : Petrel

FVIT                                   -- Generated : Petrel

FWPR                                   -- Generated : Petrel

FOPR                                   -- Generated : Petrel

FGPR                                   -- Generated : Petrel

FWPT                                   -- Generated : Petrel

FOPT                                   -- Generated : Petrel

FGPT                                   -- Generated : Petrel

FPR                                    -- Generated : Petrel

FWIP                                   -- Generated : Petrel

FOIPG                                  -- Generated : Petrel

FGIPL                                  -- Generated : Petrel

FOIP                                   -- Generated : Petrel

FOIPL                                  -- Generated : Petrel

FGIP                                   -- Generated : Petrel

FGIPG                                  -- Generated : Petrel

FWIR                                   -- Generated : Petrel

FOIR                                   -- Generated : Petrel

FGIR                                   -- Generated : Petrel

FWIT                                   -- Generated : Petrel

FOIT                                   -- Generated : Petrel

FGIT                                   -- Generated : Petrel

FGOR                                   -- Generated : Petrel

WBHP
'GAS WELL' 'TOR WELL' 'CER WELL' /

WBHPH
'GAS WELL' 'TOR WELL' 'CER WELL' /

WWIR
'TOR WELL' /

WWIRH
'TOR WELL' /

WGIR
'GAS WELL' /

WGIRH
'GAS WELL' /

WWIT
'TOR WELL' /

WGIT
'GAS WELL' /

WVPR
'CER WELL' /

WVPT
'CER WELL' /

WVIR
'GAS WELL' 'TOR WELL' /

WVIT
'GAS WELL' 'TOR WELL' /

WGOR
'CER WELL' /

WWPR
/

WOPR
/

WGPR
/

WLPR
/

WWPRH
/

WOPRH
/

WGPRH
/

WLPRH
/

SUMTHIN                                -- Generated : Petrel
  1 /

