-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.1 (64-bit) Schlumberger
-- User name   : ntvuong
-- Date        : Wednesday, June 17 2020 15:20:43
-- Project     : 40402.pet
-- Generated ]

MINPV
 15 /

MESSAGES
 10*10000000 /

INIT                                   -- Generated : Petrel

RPTINIT                                -- Generated : Petrel
  AREAX AREAY AREAZ DZMTRXV IONROCK MULTPV MULTX MULTY MULTZ MULTX- MULTY- MULTZ- ROCKFRAC /

GRIDFILE                               -- Generated : Petrel
  0 1 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

MAPUNITS                               -- Generated : Petrel
  METRES /

MAPAXES                                -- Generated : Petrel
  0.00 3000.00 0.00 4000.00 1000.00 4000.00 /

PINCH                                  -- Generated : Petrel
  /

