-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2016.1 (64-bit) Schlumberger
-- User name   : ntvuong
-- Date        : Wednesday, June 17 2020 15:20:44
-- Project     : 40402.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
          3500          310         4500            0         3500            0 0 0 0 /

RPTRST                                 -- Generated : Petrel
  BASIC=6 /

RPTSOL                                 -- Generated : Petrel
  RESTART=2 FIP /

